spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: wang159357

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

#日志级别
logging:
  level:
    root: info
    com.lrm: debug
  file:
    path: log/blog-dev.log


